### ISSUE TITLE
support PostCSS 8?

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [Timer/cssnano-simple#10]
The `cssnano-preset-simple` already releasing [v2.0.0](https://github.com/Timer/cssnano-preset-simple/releases/tag/v2.0.0) with PostCSS 8 support https://github.com/Timer/cssnano-preset-simple/commit/42a4d113af03d526fda8cc7100c4fd768a7d9f85
Do we have plan to upgrade the `cssnano-simple` also?

Mentioned on https://github.com/vercel/next.js/pull/17415#pullrequestreview-511712472

**Comment by Timer** [comment]
Absolutely! Do you have time to send a PR?
