### ISSUE TITLE
Version 1.2.1 breaks FontAwesome

### ISSUE THREAD

**Issue by francofantini** [Timer/cssnano-simple#7]
I've just updated form Nextjs 10.0.1 to 10.0.2 which updates cssnano-simple to 1.2.1 and FontAwesome Icons broke

With 1.2.0 (Nextjs 10.0.1):
![image](https://user-images.githubusercontent.com/11973156/99616562-43beb080-29fc-11eb-8150-fbc05146dd1d.png)
![image](https://user-images.githubusercontent.com/11973156/99616577-4c16eb80-29fc-11eb-9233-e190b511cef8.png)

WIth 1.2.1 (Nextjs 10.0.2):
![image](https://user-images.githubusercontent.com/11973156/99616538-3a354880-29fc-11eb-898f-5dedaad9b9af.png)
![image](https://user-images.githubusercontent.com/11973156/99616603-5b963480-29fc-11eb-8944-3740ce7cdb90.png)

Do you know how to fix this?

**Comment by Timer** [comment]
Could you provide a full reproduction?

**Comment by francofantini** [comment]
I wasn't able to reproduce this issue on codesandbox but i was able to fix it doing this

```
import Head from "next/head";
import { config, dom } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
...
return (
  <div>
    <Head><style>{dom.css()}</style></Head>
    ...
  </div>
);
```

_Originally posted by @svachalek in https://github.com/FortAwesome/react-fontawesome/issues/284#issuecomment-691707228_
